# Generated by Django 5.1.1 on 2025-09-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=120)),
                ('sub_location', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Project Number')),
                ('d_number', models.CharField(blank=True, max_length=50, verbose_name='D-nr')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('client_name', models.CharField(max_length=200, verbose_name='Requestor')),
                ('devices', models.CharField(blank=True, max_length=255, verbose_name='Device')),
                ('date_received', models.DateField(verbose_name='Income Date')),
                ('date_due', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('REVIEW', 'Review'), ('DONE', 'Done'), ('CANCELLED', 'Canceled')], default='BACKLOG', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.location')),
            ],
        ),
    ]
