# Generated by Django 5.1.1 on 2025-09-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('change_project_status', 'Może zmieniać status projektu (Kanban)')]},
        ),
    ]
