# Generated by Django 5.1.1 on 2025-09-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcost',
            options={'permissions': [('review_costs', 'Może przeglądać i akceptować koszty')]},
        ),
    ]
