# Generated by Django 5.1.1 on 2025-09-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheetentry',
            options={'permissions': [('review_timesheets', 'Może przeglądać i akceptować wpisy godzin')]},
        ),
    ]
